SET SERVEROUTPUT ON;

CREATE OR REPLACE PROCEDURE CONSOLA_LABERINTO IS
  -- DECIDIR SI LLAMO A UNA FUNCION O A LA OTRA
  IMPRIMIR_ASCII BOOLEAN := &IMPRIMIR_COMO_CARACTERES;
  
  -- RETORNO
  RECORRIDO VARCHAR2(3000);
  
  -- DIMENSIONES
  ANCHO NUMBER := &ANCHO_LABERINTO;
  ALTO NUMBER := &ALTO_LABERINTO;
  
  -- COORDENADAS INICIALES
  START_X NUMBER := &X1_LABERINTO;
  START_Y NUMBER := &Y1_LABERINTO;
  
  -- COORDENADAS FINALES
  END_X NUMBER := &X2_LABERINTO;
  END_Y NUMBER := &Y2_LABERINTO;
  
BEGIN
  IF IMPRIMIR_ASCII THEN
    SELECT LABERINTO_ASCII(ANCHO,ALTO,START_X,START_Y,END_X,END_Y) 
    INTO RECORRIDO FROM DUAL;
  ELSE
    SELECT LABERINTO(ANCHO,ALTO,START_X,START_Y,END_X,END_Y) 
    INTO RECORRIDO FROM DUAL;
  END IF;
  
  -- IMPRIMO EL RECORRIDO
  DBMS_OUTPUT.PUT_LINE(RECORRIDO);
END;
/

-- EJECUCION DEL PROCEDIMIENTO
BEGIN
  CONSOLA_LABERINTO;
END;
