create or replace FUNCTION LABERINTO_ARCHIVO 
(NOMBRE_ARCHIVO VARCHAR2)
RETURN VARCHAR2 IS
  V_ARCHIVO UTL_FILE.FILE_TYPE;
  V_LINEA VARCHAR2(1024);
  V_CONTENIDO VARCHAR2(2048);

BEGIN
  V_ARCHIVO := UTL_FILE.FOPEN ('DIR_LABERINTO', NOMBRE_ARCHIVO, 'R');

  LOOP
    UTL_FILE.GET_LINE (V_ARCHIVO, V_LINEA);
    V_CONTENIDO := V_CONTENIDO || V_LINEA || CHR(10);
  END LOOP;

EXCEPTION
  WHEN NO_DATA_FOUND THEN
    UTL_FILE.FCLOSE(V_ARCHIVO);
    RETURN '{"ERRORES":"NO", "MENSAJE":"'||V_CONTENIDO||' "}';

  WHEN UTL_FILE.ACCESS_DENIED THEN
    RETURN '{"ERRORES":"SI", "MENSAJE":"Upps, no hay permisos de lectura."}';

  WHEN UTL_FILE.INVALID_OPERATION THEN
    RETURN '{"ERRORES":"SI", "MENSAJE":"Upps, el archivo no existe."}';
END LABERINTO_ARCHIVO;
